name: Build latest container image
on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - closed

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          build-args: |
            GIT_COMMIT_SHA=${{ github.sha }}
            GIT_REPOSITORY_URL=https://github.com/${{ github.repository }}
            VERSION=${{ github.ref_name }}
          push: true
          tags: mastodon/fediscoverer:latest
